### ISSUE TITLE
登录流程中按钮点击区域太小，应该整个 button 都能点击

### ISSUE THREAD

**Issue by AmazingAng** [WTFAcademy/frontend#101]
![image](https://github.com/WTFAcademy/frontend/assets/14728591/d69f65ee-3b1c-4101-a41f-b9c0d3e5609c)

**Comment by greyhao** [comment]
@AmazingAng 已经修复，可以验证下，如果没有问题可以关闭该了

**Comment by AmazingAng** [comment]
好的 感谢贡献！
