### ISSUE TITLE
领取习题NFT出错

### ISSUE THREAD

**Issue by huangqian1985** [WTFAcademy/frontend#155]
![微信图片_20240418115818](https://github.com/WTFAcademy/frontend/assets/4954644/b460a454-19a5-4e28-83cd-54717142de7a)

**Comment by JakeXu** [comment]
Goerli 测试网应该在今年1月废弃了, 但是我在Sepolia上也是失败的 @chongqiangchen @0xb00lean

**Comment by AmazingAng** [comment]
已部署到base链
